"""add state column

Revision ID: e4c487fc6ea2
Revises: 57c98bc9be83
Create Date: 2026-03-02 19:34:26.031430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4c487fc6ea2'
down_revision: Union[str, None] = '57c98bc9be83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('state', sa.String(length=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'state')
    # ### end Alembic commands ###
